### ISSUE TITLE
热门糗事 的翻页显示异常

### ISSUE THREAD

**Issue by holyzfy** [anpho/qsbk#13]
第一页显示3条，第2页显示4条，第3页显示1条；
再翻页开始重复刚才的情景（显示内容也在有规律的重复）

上个月翻页是正常的，记不清具体时间了

**Comment by anphorea** [comment]
没有这个栏目。
你指的是 排行 / 本月吗？
测试正常。

**Comment by holyzfy** [comment]
是webworks版，现在的显示从第2页开始每页只显示两条，内容也在重复
（刚在bb world里看到这个版本停更了）

**Comment by anphorea** [comment]
嗯。。源码都不一定还能找得着了。
